/* VideoFormatTypes */

// VideoFormatTypes
// sync download menu tag
// format no
#define VIDEO_FORMAT_NO_NONE		-1
#define VIDEO_FORMAT_NO_NORMAL		0
#define VIDEO_FORMAT_NO_HQ			1	// not used
#define VIDEO_FORMAT_NO_HIGH		2
#define VIDEO_FORMAT_NO_HD			3
#define VIDEO_FORMAT_NO_FMT_34		4
#define VIDEO_FORMAT_NO_FMT_35		5
#define VIDEO_FORMAT_NO_HD_1080		6
#define VIDEO_FORMAT_NO_WEBM_43		11
#define VIDEO_FORMAT_NO_WEBM_44		12
#define VIDEO_FORMAT_NO_WEBM_45		13
#define VIDEO_FORMAT_NO_ORIGINAL	14
#define VIDEO_FORMAT_NO_WEBM_46		15

/* unused
#define VIDEO_FORMAT_NO_TITLE_NORMAL	@"FLV"
#define VIDEO_FORMAT_NO_TITLE_HQ		@"HQ"
#define VIDEO_FORMAT_NO_TITLE_HIGH		@"HIGH"
#define VIDEO_FORMAT_NO_TITLE_HD		@"HD"
#define VIDEO_FORMAT_NO_TITLE_FMT_34	@"FMT34"
#define VIDEO_FORMAT_NO_TITLE_FMT_35	@"FMT35"
#define VIDEO_FORMAT_NO_TITLE_HD_1080	@"HD/1080"
#define VIDEO_FORMAT_NO_TITLE_WEBM_43	@"WEBM_43"
#define VIDEO_FORMAT_NO_TITLE_WEBM_44	@"WEBM_44"
#define VIDEO_FORMAT_NO_TITLE_WEBM_45	@"WEBM_43"
#define VIDEO_FORMAT_NO_TITLE_ORIGINAL	@"ORIGINAL"
*/

// format map no
#define VIDEO_FORMAT_MAP_NONE		0
#define VIDEO_FORMAT_MAP_NORMAL		5
#define VIDEO_FORMAT_MAP_HQ			6
#define VIDEO_FORMAT_MAP_HIGH		18
#define VIDEO_FORMAT_MAP_HD			22
#define VIDEO_FORMAT_MAP_FMT_34		34
#define VIDEO_FORMAT_MAP_FMT_35		35
#define VIDEO_FORMAT_MAP_HD_1080	37
#define VIDEO_FORMAT_MAP_WEBM_43	43
#define VIDEO_FORMAT_MAP_WEBM_44	44
#define VIDEO_FORMAT_MAP_WEBM_45	45
#define VIDEO_FORMAT_MAP_WEBM_46	46
#define VIDEO_FORMAT_MAP_ORIGINAL	38

// name
#define VIDEO_FORMAT_NAME_NONE		@""
#define VIDEO_FORMAT_NAME_NORMAL	@"FLV"
#define VIDEO_FORMAT_NAME_HQ		@"HQ"
#define VIDEO_FORMAT_NAME_HIGH		@"MP4"
#define VIDEO_FORMAT_NAME_HD		@"HD"
#define VIDEO_FORMAT_NAME_FMT_34	@"FMT34"
#define VIDEO_FORMAT_NAME_FMT_35	@"FMT35"
#define VIDEO_FORMAT_NAME_HD_1080	@"HD/1080"
#define VIDEO_FORMAT_NAME_WEBM_43	@"WEBM43"
#define VIDEO_FORMAT_NAME_WEBM_44	@"WEBM44"
#define VIDEO_FORMAT_NAME_WEBM_45	@"WEBM45"
#define VIDEO_FORMAT_NAME_WEBM_46	@"WEBM46"
#define VIDEO_FORMAT_NAME_ORIGINAL	@"ORIGINAL"

// description
#define VIDEO_FORMAT_DESC_NONE		@""
#define VIDEO_FORMAT_DESC_NORMAL	@"LQ /FLV/H.263/MP3"
#define VIDEO_FORMAT_DESC_HQ		@"HQ /FLV/H.263/MP3"
#define VIDEO_FORMAT_DESC_HIGH		@"SD /MP4/H.264/AAC"
#define VIDEO_FORMAT_DESC_HD		@"HD720p /MP4/H.264/AAC"
#define VIDEO_FORMAT_DESC_FMT_34	@"360p /FLV/H.264/AAC"
#define VIDEO_FORMAT_DESC_FMT_35	@"480p /FLV/H.264/AAC"
#define VIDEO_FORMAT_DESC_HD_1080	@"HD1080p /MP4/H.264/AAC"
#define VIDEO_FORMAT_DESC_WEBM_43	@"360p /WebM/VP8/vorb"
#define VIDEO_FORMAT_DESC_WEBM_44	@"480p /WebM/VP8/vorb"
#define VIDEO_FORMAT_DESC_WEBM_45	@"HD720p /WebM/VP8/vorb"
#define VIDEO_FORMAT_DESC_WEBM_46	@"HD1080p /WebM/VP8/vorb"
#define VIDEO_FORMAT_DESC_ORIGINAL	@"ORIGINAL(4k2k) /MP4/H.264/AAC"

// format map order
#define VIDEO_FORMAT_ORDER_NONE		0
#define VIDEO_FORMAT_ORDER_NORMAL	1
#define VIDEO_FORMAT_ORDER_HQ		2
#define VIDEO_FORMAT_ORDER_HIGH		3
#define VIDEO_FORMAT_ORDER_HD		4
#define VIDEO_FORMAT_ORDER_FMT_34	6
#define VIDEO_FORMAT_ORDER_FMT_35	7
#define VIDEO_FORMAT_ORDER_HD_1080	5
#define VIDEO_FORMAT_ORDER_WEBM_43	8
#define VIDEO_FORMAT_ORDER_WEBM_44	9
#define VIDEO_FORMAT_ORDER_WEBM_45	10
#define VIDEO_FORMAT_ORDER_WEBM_46	11
#define VIDEO_FORMAT_ORDER_ORIGINAL	12

// format type
#define VIDEO_FORMAT_FILE_TYPE_FLV		0	// FLV
#define VIDEO_FORMAT_FILE_TYPE_MP4		1	// MP4
#define VIDEO_FORMAT_FILE_TYPE_WEBM		2	// WEBM

#define VIDEO_FORMAT_TYPE_NORMAL	0
#define VIDEO_FORMAT_TYPE_HQ		0
#define VIDEO_FORMAT_TYPE_HIGH		1
#define VIDEO_FORMAT_TYPE_HD		1
#define VIDEO_FORMAT_TYPE_FMT_34	0
#define VIDEO_FORMAT_TYPE_FMT_35	0
#define VIDEO_FORMAT_TYPE_HD_1080	1
#define VIDEO_FORMAT_TYPE_WEBM_43	2
#define VIDEO_FORMAT_TYPE_WEBM_44	2
#define VIDEO_FORMAT_TYPE_WEBM_45	2
#define VIDEO_FORMAT_TYPE_WEBM_46	2
#define VIDEO_FORMAT_TYPE_ORIGINAL	1

